{"uuid": "51147cee-a6d2-4ebc-9be7-59f8085293c9", "children": ["9ec327a6-3c45-4e4c-a1d7-0baaf702f6da"], "befores": [{"name": "_xunit_setup_function_fixture_test_1", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=120.0.6099.130)\nStacktrace:\n\tGetHandleVerifier [0x00007FF79FE22142+3514994]\n\t(No symbol) [0x00007FF79FA40CE2]\n\t(No symbol) [0x00007FF79F8E76AA]\n\t(No symbol) [0x00007FF79F8C0AFD]\n\t(No symbol) [0x00007FF79F95CB1B]\n\t(No symbol) [0x00007FF79F97218F]\n\t(No symbol) [0x00007FF79F955D93]\n\t(No symbol) [0x00007FF79F924BDC]\n\t(No symbol) [0x00007FF79F925C64]\n\tGetHandleVerifier [0x00007FF79FE4E16B+3695259]\n\tGetHandleVerifier [0x00007FF79FEA6737+4057191]\n\tGetHandleVerifier [0x00007FF79FE9E4E3+4023827]\n\tGetHandleVerifier [0x00007FF79FB704F9+689705]\n\t(No symbol) [0x00007FF79FA4C048]\n\t(No symbol) [0x00007FF79FA48044]\n\t(No symbol) [0x00007FF79FA481C9]\n\t(No symbol) [0x00007FF79FA388C4]\n\tBaseThreadInitThunk [0x00007FFEB1477344+20]\n\tRtlUserThreadStart [0x00007FFEB2FC26B1+33]\n\n", "trace": "  File \"D:\\Python\\Selenium\\Jenkins_project\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python\\Selenium\\Jenkins_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python\\Selenium\\Jenkins_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\Python\\Selenium\\Jenkins_project\\Lib\\site-packages\\_pytest\\python.py\", line 597, in xunit_setup_function_fixture\n    _call_with_optional_argument(setup_function, request.function)\n  File \"D:\\Python\\Selenium\\Jenkins_project\\Lib\\site-packages\\_pytest\\python.py\", line 778, in _call_with_optional_argument\n    func()\n  File \"D:\\Python\\Selenium\\Jenkins_project\\test_1.py\", line 14, in setup_function\n    driver.maximize_window()\n  File \"D:\\Python\\Selenium\\Jenkins_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 500, in maximize_window\n    self.execute(command, None)\n  File \"D:\\Python\\Selenium\\Jenkins_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python\\Selenium\\Jenkins_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1704007505632, "stop": 1704007512619}], "start": 1704007505632, "stop": 1704007513004}